spring.application.name=spring-ai-app

#Ollma setup - mistral is default model, you can change it to any model you have in ollama pulled on local machine
spring.ollama.url=http://localhost:11434
spring.ollama.model=mistral

# Google Gemini setup - make sure to set the GOOGLE_GEMINI_API_KEY environment variable with your API key
spring.ai.google.genai.api-key=${GOOGLE_GEMINI_API_KEY}
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview

# OpenAI setup - make sure to set the OPENAI_API_KEY environment variable with your API key
spring.ai.openai.api-key=${OPENAI_API_KEY}

# 1. Chat models
spring.ai.openai.chat.options.model=gpt-4-0613

# 2. Image generation
spring.ai.openai.image.options.model=dall-e-3

# 3. Speech-to-text
spring.ai.openai.audio.transcription.model=whisper-1

# 4. Text-to-speech
spring.ai.openai.audio.speech.model=gpt-4o-mini-tts

